import { expect, test } from "@playwright/test"
import { PageManager } from "../src/pages/pageManager"

test('first test', async ({page}) => {
  await page.goto("https://oikocredit--ltp.sandbox.my.salesforce.com/")
  const pm = new PageManager(page)
  await pm.onLoginPage().loginUser("jmancuello@oikocredit.org.ltp", "Nina23!!")
  await pm.onHomePage().menu.clickOnTab("Leads")
  await pm.onLeadsPage().clickNewLead()
  await pm.onLeadsPage().selectInflow()
  await pm.onLeadsPage().selectLeadSource("Event")
  await pm.onLeadsPage().fillInWithRandomFirstName()
  await pm.onLeadsPage().fillInWithRandomLastName()
  await pm.onLeadsPage().fillInWithRandomEmail()
  await pm.onLeadsPage().fillInWithRandomAccountName()
  await pm.onLeadsPage().selectCountry("Germany")
  await pm.onLeadsPage().saveTheForm()
  expect(await pm.onLeadsPage().isLeadCreatedMessageDisplayed()).toBe(true)
  await pm.onLeadProfilePage().menu.clickOnTab("Leads")
  expect(await pm.onLeadsPage().isNewLeadInList()).toBe(true)
})

test('second test', async ({page}) => {
  await page.goto("https://oikocredit--ltp.sandbox.my.salesforce.com/")
  const pm = new PageManager(page)
  await pm.onLoginPage().loginUser("jmancuello@oikocredit.org.ltp", "Nina23!!")
  await pm.onHomePage().menu.clickOnTab("Leads")
  await pm.onLeadsPage().selectFirstLeadInList()
  await pm.onLeadProfilePage().saveInContextLead("name")
  await pm.onLeadProfilePage().clickEditLead()
  await pm.onLeadProfilePage().fillInWithRandomMobile()
  await pm.onLeadProfilePage().saveChanges()
  expect(await pm.onLeadProfilePage().isSavedChangesMessageDisplayed()).toBe(true)
  expect(await pm.onLeadProfilePage().isNewMobileDisplayed()).toBe(true)
})

test('third test', async ({page}) => {
  await page.goto("https://oikocredit--ltp.sandbox.my.salesforce.com/")
  const pm = new PageManager(page)
  await pm.onLoginPage().loginUser("jmancuello@oikocredit.org.ltp", "Nina23!!")
  await pm.onHomePage().menu.clickOnTab("Leads")
  await pm.onLeadsPage().selectFirstLeadInList()
  await pm.onLeadProfilePage().saveInContextLead("accountName")
  await pm.onLeadProfilePage().clickConvertLead()
  await pm.onLeadProfilePage().selectRecordType("Prospect Individual")
  await pm.onLeadProfilePage().convertLead()
  expect(await pm.onLeadProfilePage().isLeadConvertedMessageDisplayed()).toBe(true)
  await pm.onLeadsPage().menu.clickOnTab("Accounts")
  await pm.onAccountsPage().searchAccount()
  await pm.onAccountsPage().selectAccountRetrieved()
  expect(await pm.onAccountProfilePage().isRecordType("Prospect Individual")).toBe(true)
  expect(await pm.onAccountProfilePage().isStatus("Pending Signup")).toBe(true)
})