name: Playwright Cucumber Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'  # Ejecuta a las 9 AM UTC diariamente

env:
  # Establece aquí las variables de entorno que reemplazarán tu test.properties
  SALESFORCE_LTP_USER: ${{ secrets.SALESFORCE_LTP_USER }}
  SALESFORCE_LTP_PASSWORD: ${{ secrets.SALESFORCE_LTP_PASSWORD }}
  # Agrega otras variables que necesites

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Create reports directory and copy images
      run: |
        mkdir -p reports/images
        cp -r resources/images/* reports/images/
        
    - name: Run tests with report generation
      run: npm run test:with-report
      
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report
        path: reports/